device_info:
  name: UniFi
mqtt:
  host: localhost
  port: 1883
  connection:
    keepalive: 15
    retry_limit: 30
    reconnect_interval: 10
homeassistant:
  enabled: true
  discovery_prefix: homeassistant
unifi_controller:
  url: localhost
  port: 8443
  username: username
  password: password
logging:
  level: info
