happy_path_devices_json_response: str = """{
    "meta": {
        "rc": "ok"
    },
    "data": [
        {
            "_id": "MOCKED_ID",
            "adopted": true,
            "anomalies": -1,
            "anon_id": "ef1c5fdb-7f24-4806-88d9-76db276a9b01",
            "architecture": "armv7l",
            "board_rev": 8,
            "cfgversion": "9b584e5b55742366",
            "config_network": {
                "type": "dhcp"
            },
            "connected_at": 1659811098,
            "dot1x_portctrl_enabled": false,
            "ethernet_table": [
                {
                    "mac": "b4:fb:e4:b6:6f:12",
                    "num_port": 26,
                    "name": "eth0"
                },
                {
                    "mac": "b4:fb:e4:b6:6f:13",
                    "name": "srv0"
                }
            ],
            "flowctrl_enabled": false,
            "fw_caps": -1488265691,
            "gateway_mac": "00:0d:b9:52:45:50",
            "has_fan": true,
            "has_temperature": true,
            "hash_id": "68d976db276a9b01",
            "hw_caps": 0,
            "inform_ip": "10.10.0.5",
            "inform_url": "http://10.10.0.5:8080/inform",
            "internet": true,
            "ip": "10.10.0.2",
            "jumboframe_enabled": false,
            "kernel_version": "3.6.5",
            "led_override": "on",
            "led_override_color": "#0000FF",
            "led_override_color_brightness": 100,
            "license_state": "registered",
            "mac": "b4:fb:e4:b6:6f:12",
            "manufacturer_id": 2,
            "mgmt_network_id": "6070c964a61f7408a7706056",
            "model": "US24P250",
            "model_in_eol": false,
            "model_in_lts": false,
            "model_incompatible": false,
            "name": "unifi-switch",
            "port_overrides": [
                {
                    "name": "MOCKED Port 1",
                    "port_idx": 1,
                    "poe_mode": "pasv24",
                    "portconf_id": "60c0bdca0da23303beb7f799",
                    "port_security_mac_address": [],
                    "stp_port_mode": true,
                    "autoneg": true,
                    "port_security_enabled": false
                },
                {
                    "name": "MOCKED Port 2",
                    "port_idx": 2,
                    "poe_mode": "off",
                    "portconf_id": "6070c964a61f7408a770605c",
                    "port_security_mac_address": [],
                    "stp_port_mode": true,
                    "autoneg": true,
                    "port_security_enabled": false
                },
                {
                    "name": "MOCKED Port 3",
                    "port_idx": 3,
                    "poe_mode": "auto",
                    "portconf_id": "6070c964a61f7408a770605a",
                    "port_security_mac_address": [],
                    "stp_port_mode": true,
                    "autoneg": true,
                    "port_security_enabled": false
                },
                {
                    "name": "MOCKED Port 4",
                    "port_idx": 4,
                    "poe_mode": "off",
                    "portconf_id": "60c0bd9d0da23303beb7f793",
                    "port_security_mac_address": [],
                    "stp_port_mode": true,
                    "autoneg": true
                },
                {
                    "stp_port_mode": true,
                    "autoneg": true,
                    "port_idx": 5,
                    "name": "MOCKED Port 5",
                    "poe_mode": "off",
                    "portconf_id": "6070c964a61f7408a770605c",
                    "port_security_mac_address": []
                },
                {
                    "name": "MOCKED Port 6",
                    "port_security_mac_address": [],
                    "stp_port_mode": true,
                    "portconf_id": "60c0bd9d0da23303beb7f793",
                    "autoneg": true,
                    "port_idx": 6,
                    "poe_mode": "off"
                },
                {
                    "poe_mode": "off",
                    "stp_port_mode": true,
                    "port_security_mac_address": [],
                    "port_idx": 7,
                    "portconf_id": "6070c964a61f7408a770605c",
                    "name": "MOCKED Port 7",
                    "autoneg": true
                },
                {
                    "name": "Port 8",
                    "port_idx": 8,
                    "poe_mode": "auto",
                    "portconf_id": "6070c964a61f7408a770605c"
                },
                {
                    "port_security_enabled": false,
                    "autoneg": true,
                    "portconf_id": "60717a89a61f7408a7706281",
                    "stp_port_mode": true,
                    "port_idx": 9,
                    "poe_mode": "off",
                    "name": "MOCKED Port 9",
                    "port_security_mac_address": []
                },
                {
                    "name": "MOCKED Port 10",
                    "autoneg": true,
                    "portconf_id": "60717a89a61f7408a7706281",
                    "poe_mode": "off",
                    "port_idx": 10,
                    "stp_port_mode": true,
                    "port_security_mac_address": [],
                    "port_security_enabled": false
                },
                {
                    "name": "MOCKED Port 11",
                    "port_idx": 11,
                    "poe_mode": "off",
                    "portconf_id": "60c0bd9d0da23303beb7f793",
                    "port_security_mac_address": [],
                    "stp_port_mode": true,
                    "autoneg": true,
                    "port_security_enabled": false
                },
                {
                    "name": "MOCKED Port 12",
                    "port_idx": 12,
                    "poe_mode": "off",
                    "portconf_id": "60717a89a61f7408a7706281",
                    "port_security_mac_address": [],
                    "stp_port_mode": true,
                    "autoneg": true,
                    "port_security_enabled": false
                },
                {
                    "autoneg": true,
                    "stp_port_mode": true,
                    "portconf_id": "6070c964a61f7408a770605c",
                    "poe_mode": "off",
                    "port_idx": 13,
                    "port_security_mac_address": [],
                    "name": "MOCKED Port 13"
                },
                {
                    "portconf_id": "6070c964a61f7408a770605c",
                    "autoneg": true,
                    "stp_port_mode": true,
                    "port_security_mac_address": [],
                    "name": "MOCKED Port 14",
                    "port_idx": 14,
                    "poe_mode": "off"
                },
                {
                    "port_idx": 15,
                    "name": "MOCKED Port 15",
                    "autoneg": true,
                    "poe_mode": "off",
                    "stp_port_mode": true,
                    "port_security_mac_address": [],
                    "portconf_id": "6070c964a61f7408a770605c",
                    "port_security_enabled": false
                },
                {
                    "name": "MOCKED Port 16",
                    "port_idx": 16,
                    "poe_mode": "off",
                    "portconf_id": "60c0bdca0da23303beb7f799",
                    "port_security_mac_address": [],
                    "stp_port_mode": true,
                    "autoneg": true,
                    "port_security_enabled": false
                },
                {
                    "name": "MOCKED Port 17",
                    "port_idx": 17,
                    "poe_mode": "auto",
                    "portconf_id": "60c0bd9d0da23303beb7f793",
                    "port_security_mac_address": [],
                    "stp_port_mode": true,
                    "autoneg": true,
                    "port_security_enabled": false
                },
                {
                    "name": "MOCKED Port 18",
                    "port_idx": 18,
                    "poe_mode": "off",
                    "portconf_id": "6070c964a61f7408a770605c",
                    "port_security_mac_address": [],
                    "stp_port_mode": true,
                    "autoneg": true,
                    "port_security_enabled": false
                },
                {
                    "autoneg": true,
                    "port_security_mac_address": [],
                    "stp_port_mode": true,
                    "poe_mode": "off",
                    "name": "MOCKED Port 19",
                    "portconf_id": "60c0bd9d0da23303beb7f793",
                    "port_idx": 19
                },
                {
                    "name": "MOCKED Port 20",
                    "port_idx": 20,
                    "poe_mode": "off",
                    "portconf_id": "6070c964a61f7408a770605c",
                    "port_security_mac_address": [],
                    "stp_port_mode": true,
                    "autoneg": true,
                    "port_security_enabled": false
                },
                {
                    "autoneg": true,
                    "port_idx": 21,
                    "port_security_mac_address": [],
                    "portconf_id": "60c0bd9d0da23303beb7f793",
                    "name": "MOCKED Port 21",
                    "poe_mode": "off",
                    "stp_port_mode": true
                },
                {
                    "port_idx": 22,
                    "poe_mode": "off",
                    "port_security_mac_address": [],
                    "autoneg": true,
                    "name": "MOCKED Port 22",
                    "portconf_id": "6070c964a61f7408a770605c",
                    "stp_port_mode": true
                },
                {
                    "portconf_id": "6070c964a61f7408a770605a",
                    "autoneg": true,
                    "poe_mode": "off",
                    "port_idx": 23,
                    "stp_port_mode": true,
                    "name": "MOCKED Port 23",
                    "port_security_mac_address": []
                },
                {
                    "name": "MOCKED Port 24",
                    "port_idx": 24,
                    "poe_mode": "off",
                    "portconf_id": "622204f0cbfa12042d704038",
                    "port_security_mac_address": [],
                    "stp_port_mode": true,
                    "autoneg": true,
                    "port_security_enabled": false
                },
                {
                    "stp_port_mode": true,
                    "autoneg": true,
                    "port_idx": 25,
                    "port_security_mac_address": [],
                    "portconf_id": "6070c964a61f7408a770605b"
                },
                {
                    "port_security_mac_address": [],
                    "autoneg": true,
                    "portconf_id": "6070c964a61f7408a770605b",
                    "stp_port_mode": true,
                    "port_idx": 26
                }
            ],
            "port_table": [
                {
                    "port_idx": 1,
                    "media": "GE",
                    "port_poe": true,
                    "poe_caps": 7,
                    "speed_caps": 1048623,
                    "op_mode": "switch",
                    "portconf_id": "6070c964a61f7408a770605a",
                    "poe_mode": "pasv24",
                    "anomalies": 0,
                    "autoneg": true,
                    "dot1x_mode": "unknown",
                    "dot1x_status": "disabled",
                    "enable": true,
                    "flowctrl_rx": false,
                    "flowctrl_tx": false,
                    "full_duplex": true,
                    "is_uplink": false,
                    "jumbo": false,
                    "mac_table": [
                        {
                            "age": 2896,
                            "hostname": "aircube-104",
                            "ip": "10.10.4.2",
                            "mac": "26:5a:4c:e9:2d:3a",
                            "static": false,
                            "uptime": 100101,
                            "vlan": 104
                        },
                        {
                            "age": 14,
                            "hostname": "robotic-mower",
                            "ip": "10.10.4.10",
                            "mac": "1c:9d:c2:dc:ed:c4",
                            "static": false,
                            "uptime": 100084,
                            "vlan": 104
                        },
                        {
                            "age": 2886,
                            "hostname": "aircube-102",
                            "ip": "10.10.2.17",
                            "mac": "26:5a:4c:e9:2d:3a",
                            "static": false,
                            "uptime": 100103,
                            "vlan": 102
                        }
                    ],
                    "poe_class": "Unknown",
                    "poe_current": "0.00",
                    "poe_enable": true,
                    "poe_good": false,
                    "poe_power": "0.00",
                    "poe_voltage": "24.00",
                    "rx_broadcast": 11902,
                    "rx_bytes": 42726228,
                    "rx_dropped": 55,
                    "rx_errors": 0,
                    "rx_multicast": 2684,
                    "rx_packets": 192974,
                    "satisfaction": 90,
                    "satisfaction_reason": 1,
                    "speed": 100,
                    "stp_pathcost": 200000,
                    "stp_state": "forwarding",
                    "tx_broadcast": 46945,
                    "tx_bytes": 64271456,
                    "tx_dropped": 0,
                    "tx_errors": 0,
                    "tx_multicast": 469225,
                    "tx_packets": 678586,
                    "up": true,
                    "tx_bytes-r": 125,
                    "rx_bytes-r": 26,
                    "bytes-r": 151,
                    "name": "AirCube",
                    "port_security_mac_address": [],
                    "stp_port_mode": true,
                    "port_security_enabled": false,
                    "masked": false,
                    "aggregated_by": false
                },
                {
                    "port_idx": 2,
                    "media": "GE",
                    "port_poe": true,
                    "poe_caps": 7,
                    "speed_caps": 1048623,
                    "op_mode": "switch",
                    "portconf_id": "6070c964a61f7408a770605c",
                    "poe_mode": "off",
                    "anomalies": 0,
                    "autoneg": true,
                    "dot1x_mode": "unknown",
                    "dot1x_status": "disabled",
                    "enable": true,
                    "flowctrl_rx": false,
                    "flowctrl_tx": false,
                    "full_duplex": true,
                    "is_uplink": false,
                    "jumbo": false,
                    "mac_table": [
                        {
                            "age": 2941,
                            "hostname": "unipi",
                            "ip": "10.10.0.4",
                            "mac": "b8:27:eb:13:05:53",
                            "static": false,
                            "uptime": 647353,
                            "vlan": 1,
                            "is_only_station_on_port": true
                        }
                    ],
                    "poe_class": "Unknown",
                    "poe_current": "0.00",
                    "poe_enable": false,
                    "poe_good": false,
                    "poe_power": "0.00",
                    "poe_voltage": "0.00",
                    "rx_broadcast": 36,
                    "rx_bytes": 826409351,
                    "rx_dropped": 32677,
                    "rx_errors": 0,
                    "rx_multicast": 38455,
                    "rx_packets": 2647366,
                    "satisfaction": 90,
                    "satisfaction_reason": 1,
                    "speed": 1000,
                    "stp_pathcost": 20000,
                    "stp_state": "forwarding",
                    "tx_broadcast": 61135,
                    "tx_bytes": 426943862,
                    "tx_dropped": 0,
                    "tx_errors": 0,
                    "tx_multicast": 711513,
                    "tx_packets": 4154321,
                    "up": true,
                    "tx_bytes-r": 116,
                    "rx_bytes-r": 61,
                    "bytes-r": 178,
                    "name": "2.2 Distribution Cabinet",
                    "port_security_mac_address": [],
                    "stp_port_mode": true,
                    "port_security_enabled": false,
                    "masked": false,
                    "aggregated_by": false
                },
                {
                    "port_idx": 3,
                    "media": "GE",
                    "port_poe": true,
                    "poe_caps": 7,
                    "speed_caps": 1048623,
                    "op_mode": "switch",
                    "portconf_id": "6070c964a61f7408a770605a",
                    "poe_mode": "off",
                    "anomalies": 0,
                    "autoneg": true,
                    "dot1x_mode": "unknown",
                    "dot1x_status": "disabled",
                    "enable": true,
                    "flowctrl_rx": false,
                    "flowctrl_tx": false,
                    "full_duplex": false,
                    "is_uplink": false,
                    "jumbo": false,
                    "mac_table": [],
                    "poe_class": "Unknown",
                    "poe_current": "0.00",
                    "poe_enable": false,
                    "poe_good": false,
                    "poe_power": "0.00",
                    "poe_voltage": "0.00",
                    "rx_broadcast": 215,
                    "rx_bytes": 888852,
                    "rx_dropped": 27,
                    "rx_errors": 0,
                    "rx_multicast": 618,
                    "rx_packets": 3448,
                    "satisfaction": 90,
                    "satisfaction_reason": 1,
                    "speed": 0,
                    "stp_pathcost": 0,
                    "stp_state": "disabled",
                    "tx_broadcast": 276,
                    "tx_bytes": 1204332,
                    "tx_dropped": 0,
                    "tx_errors": 0,
                    "tx_multicast": 3016,
                    "tx_packets": 5294,
                    "up": false,
                    "tx_bytes-r": 0,
                    "rx_bytes-r": 0,
                    "bytes-r": 0,
                    "name": "UniFi Access Point",
                    "port_security_mac_address": [],
                    "stp_port_mode": true,
                    "port_security_enabled": false,
                    "masked": false,
                    "aggregated_by": false
                },
                {
                    "port_idx": 4,
                    "media": "GE",
                    "port_poe": true,
                    "poe_caps": 7,
                    "speed_caps": 1048623,
                    "op_mode": "switch",
                    "portconf_id": "60c0bd9d0da23303beb7f793",
                    "poe_mode": "off",
                    "anomalies": 0,
                    "autoneg": true,
                    "dot1x_mode": "unknown",
                    "dot1x_status": "disabled",
                    "enable": true,
                    "flowctrl_rx": false,
                    "flowctrl_tx": false,
                    "full_duplex": false,
                    "is_uplink": false,
                    "jumbo": false,
                    "mac_table": [],
                    "poe_class": "Unknown",
                    "poe_current": "0.00",
                    "poe_enable": false,
                    "poe_good": false,
                    "poe_power": "0.00",
                    "poe_voltage": "0.00",
                    "rx_broadcast": 1408,
                    "rx_bytes": 2531889012,
                    "rx_dropped": 2623,
                    "rx_errors": 1,
                    "rx_multicast": 11668,
                    "rx_packets": 34030357,
                    "satisfaction": 75,
                    "satisfaction_reason": 3,
                    "speed": 0,
                    "stp_pathcost": 0,
                    "stp_state": "disabled",
                    "tx_broadcast": 50464,
                    "tx_bytes": 108149638686,
                    "tx_dropped": 0,
                    "tx_errors": 0,
                    "tx_multicast": 91654,
                    "tx_packets": 71984068,
                    "up": false,
                    "tx_bytes-r": 0,
                    "rx_bytes-r": 0,
                    "bytes-r": 0,
                    "stp_port_mode": true,
                    "port_security_mac_address": [],
                    "name": "1.4 Living Room",
                    "masked": false,
                    "aggregated_by": false
                },
                {
                    "port_idx": 5,
                    "media": "GE",
                    "port_poe": true,
                    "poe_caps": 7,
                    "speed_caps": 1048623,
                    "op_mode": "switch",
                    "portconf_id": "6070c964a61f7408a770605c",
                    "poe_mode": "off",
                    "anomalies": 0,
                    "autoneg": true,
                    "dot1x_mode": "unknown",
                    "dot1x_status": "disabled",
                    "enable": true,
                    "flowctrl_rx": false,
                    "flowctrl_tx": false,
                    "full_duplex": false,
                    "is_uplink": false,
                    "jumbo": false,
                    "mac_table": [],
                    "poe_class": "Unknown",
                    "poe_current": "0.00",
                    "poe_enable": false,
                    "poe_good": false,
                    "poe_power": "0.00",
                    "poe_voltage": "0.00",
                    "rx_broadcast": 0,
                    "rx_bytes": 0,
                    "rx_dropped": 0,
                    "rx_errors": 0,
                    "rx_multicast": 0,
                    "rx_packets": 0,
                    "satisfaction": 100,
                    "satisfaction_reason": 0,
                    "speed": 0,
                    "stp_pathcost": 0,
                    "stp_state": "disabled",
                    "tx_broadcast": 0,
                    "tx_bytes": 0,
                    "tx_dropped": 0,
                    "tx_errors": 0,
                    "tx_multicast": 0,
                    "tx_packets": 0,
                    "up": false,
                    "tx_bytes-r": 0,
                    "rx_bytes-r": 0,
                    "bytes-r": 0,
                    "stp_port_mode": true,
                    "name": "1.5 Living Room",
                    "port_security_mac_address": [],
                    "masked": false,
                    "aggregated_by": false
                },
                {
                    "port_idx": 6,
                    "media": "GE",
                    "port_poe": true,
                    "poe_caps": 7,
                    "speed_caps": 1048623,
                    "op_mode": "switch",
                    "portconf_id": "60c0bd9d0da23303beb7f793",
                    "poe_mode": "off",
                    "anomalies": 0,
                    "autoneg": true,
                    "dot1x_mode": "unknown",
                    "dot1x_status": "disabled",
                    "enable": true,
                    "flowctrl_rx": false,
                    "flowctrl_tx": false,
                    "full_duplex": false,
                    "is_uplink": false,
                    "jumbo": false,
                    "mac_table": [],
                    "poe_class": "Unknown",
                    "poe_current": "0.00",
                    "poe_enable": false,
                    "poe_good": false,
                    "poe_power": "0.00",
                    "poe_voltage": "0.00",
                    "rx_broadcast": 132,
                    "rx_bytes": 33520791,
                    "rx_dropped": 10171,
                    "rx_errors": 1,
                    "rx_multicast": 24632,
                    "rx_packets": 283784,
                    "satisfaction": 75,
                    "satisfaction_reason": 3,
                    "speed": 0,
                    "stp_pathcost": 0,
                    "stp_state": "disabled",
                    "tx_broadcast": 52376,
                    "tx_bytes": 34379156,
                    "tx_dropped": 0,
                    "tx_errors": 0,
                    "tx_multicast": 85540,
                    "tx_packets": 289232,
                    "up": false,
                    "tx_bytes-r": 0,
                    "rx_bytes-r": 0,
                    "bytes-r": 0,
                    "name": "1.6 Living Room",
                    "port_security_mac_address": [],
                    "stp_port_mode": true,
                    "masked": false,
                    "aggregated_by": false
                },
                {
                    "port_idx": 7,
                    "media": "GE",
                    "port_poe": true,
                    "poe_caps": 7,
                    "speed_caps": 1048623,
                    "op_mode": "switch",
                    "portconf_id": "6070c964a61f7408a770605c",
                    "poe_mode": "off",
                    "anomalies": 0,
                    "autoneg": true,
                    "dot1x_mode": "unknown",
                    "dot1x_status": "disabled",
                    "enable": true,
                    "flowctrl_rx": false,
                    "flowctrl_tx": false,
                    "full_duplex": false,
                    "is_uplink": false,
                    "jumbo": false,
                    "mac_table": [],
                    "poe_class": "Unknown",
                    "poe_current": "0.00",
                    "poe_enable": false,
                    "poe_good": false,
                    "poe_power": "0.00",
                    "poe_voltage": "0.00",
                    "rx_broadcast": 0,
                    "rx_bytes": 0,
                    "rx_dropped": 0,
                    "rx_errors": 0,
                    "rx_multicast": 0,
                    "rx_packets": 0,
                    "satisfaction": 100,
                    "satisfaction_reason": 0,
                    "speed": 0,
                    "stp_pathcost": 0,
                    "stp_state": "disabled",
                    "tx_broadcast": 0,
                    "tx_bytes": 0,
                    "tx_dropped": 0,
                    "tx_errors": 0,
                    "tx_multicast": 0,
                    "tx_packets": 0,
                    "up": false,
                    "tx_bytes-r": 0,
                    "rx_bytes-r": 0,
                    "bytes-r": 0,
                    "stp_port_mode": true,
                    "port_security_mac_address": [],
                    "name": "1.7 Living Room",
                    "masked": false,
                    "aggregated_by": false
                },
                {
                    "port_idx": 8,
                    "media": "GE",
                    "port_poe": true,
                    "poe_caps": 7,
                    "speed_caps": 1048623,
                    "op_mode": "switch",
                    "portconf_id": "60717a89a61f7408a7706281",
                    "poe_mode": "off",
                    "anomalies": 0,
                    "autoneg": true,
                    "dot1x_mode": "unknown",
                    "dot1x_status": "disabled",
                    "enable": true,
                    "flowctrl_rx": false,
                    "flowctrl_tx": false,
                    "full_duplex": false,
                    "is_uplink": false,
                    "jumbo": false,
                    "mac_table": [],
                    "poe_class": "Unknown",
                    "poe_current": "0.00",
                    "poe_enable": false,
                    "poe_good": false,
                    "poe_power": "0.00",
                    "poe_voltage": "0.00",
                    "rx_broadcast": 1730,
                    "rx_bytes": 1124315,
                    "rx_dropped": 0,
                    "rx_errors": 0,
                    "rx_multicast": 2,
                    "rx_packets": 12424,
                    "satisfaction": 100,
                    "satisfaction_reason": 0,
                    "speed": 0,
                    "stp_pathcost": 0,
                    "stp_state": "disabled",
                    "tx_broadcast": 8602,
                    "tx_bytes": 10146445,
                    "tx_dropped": 0,
                    "tx_errors": 0,
                    "tx_multicast": 75589,
                    "tx_packets": 92596,
                    "up": false,
                    "tx_bytes-r": 0,
                    "rx_bytes-r": 0,
                    "bytes-r": 0,
                    "name": "1.8 Children Room 2",
                    "port_security_mac_address": [],
                    "stp_port_mode": true,
                    "port_security_enabled": false,
                    "masked": false,
                    "aggregated_by": false
                },
                {
                    "port_idx": 9,
                    "media": "GE",
                    "port_poe": true,
                    "poe_caps": 7,
                    "speed_caps": 1048623,
                    "op_mode": "switch",
                    "portconf_id": "60717a89a61f7408a7706281",
                    "poe_mode": "off",
                    "anomalies": 0,
                    "autoneg": true,
                    "dot1x_mode": "unknown",
                    "dot1x_status": "disabled",
                    "enable": true,
                    "flowctrl_rx": false,
                    "flowctrl_tx": false,
                    "full_duplex": false,
                    "is_uplink": false,
                    "jumbo": false,
                    "mac_table": [],
                    "poe_class": "Unknown",
                    "poe_current": "0.00",
                    "poe_enable": false,
                    "poe_good": false,
                    "poe_power": "0.00",
                    "poe_voltage": "0.00",
                    "rx_broadcast": 0,
                    "rx_bytes": 0,
                    "rx_dropped": 0,
                    "rx_errors": 0,
                    "rx_multicast": 0,
                    "rx_packets": 0,
                    "satisfaction": 100,
                    "satisfaction_reason": 0,
                    "speed": 0,
                    "stp_pathcost": 0,
                    "stp_state": "disabled",
                    "tx_broadcast": 0,
                    "tx_bytes": 0,
                    "tx_dropped": 0,
                    "tx_errors": 0,
                    "tx_multicast": 0,
                    "tx_packets": 0,
                    "up": false,
                    "tx_bytes-r": 0,
                    "rx_bytes-r": 0,
                    "bytes-r": 0,
                    "port_security_enabled": false,
                    "stp_port_mode": true,
                    "name": "1.9 Children Room 2",
                    "port_security_mac_address": [],
                    "masked": false,
                    "aggregated_by": false
                },
                {
                    "port_idx": 10,
                    "media": "GE",
                    "port_poe": true,
                    "poe_caps": 7,
                    "speed_caps": 1048623,
                    "op_mode": "switch",
                    "portconf_id": "60717a89a61f7408a7706281",
                    "poe_mode": "off",
                    "anomalies": 0,
                    "autoneg": true,
                    "dot1x_mode": "unknown",
                    "dot1x_status": "disabled",
                    "enable": true,
                    "flowctrl_rx": false,
                    "flowctrl_tx": false,
                    "full_duplex": false,
                    "is_uplink": false,
                    "jumbo": false,
                    "mac_table": [],
                    "poe_class": "Unknown",
                    "poe_current": "0.00",
                    "poe_enable": false,
                    "poe_good": false,
                    "poe_power": "0.00",
                    "poe_voltage": "0.00",
                    "rx_broadcast": 0,
                    "rx_bytes": 0,
                    "rx_dropped": 0,
                    "rx_errors": 0,
                    "rx_multicast": 0,
                    "rx_packets": 0,
                    "satisfaction": 100,
                    "satisfaction_reason": 0,
                    "speed": 0,
                    "stp_pathcost": 0,
                    "stp_state": "disabled",
                    "tx_broadcast": 0,
                    "tx_bytes": 0,
                    "tx_dropped": 0,
                    "tx_errors": 0,
                    "tx_multicast": 0,
                    "tx_packets": 0,
                    "up": false,
                    "tx_bytes-r": 0,
                    "rx_bytes-r": 0,
                    "bytes-r": 0,
                    "name": "1.10 Children Room 2",
                    "stp_port_mode": true,
                    "port_security_mac_address": [],
                    "port_security_enabled": false,
                    "masked": false,
                    "aggregated_by": false
                },
                {
                    "port_idx": 11,
                    "media": "GE",
                    "port_poe": true,
                    "poe_caps": 7,
                    "speed_caps": 1048623,
                    "op_mode": "switch",
                    "portconf_id": "60c0bd9d0da23303beb7f793",
                    "poe_mode": "off",
                    "anomalies": 0,
                    "autoneg": true,
                    "dot1x_mode": "unknown",
                    "dot1x_status": "disabled",
                    "enable": true,
                    "flowctrl_rx": false,
                    "flowctrl_tx": false,
                    "full_duplex": false,
                    "is_uplink": false,
                    "jumbo": false,
                    "mac_table": [],
                    "poe_class": "Unknown",
                    "poe_current": "0.00",
                    "poe_enable": false,
                    "poe_good": false,
                    "poe_power": "0.00",
                    "poe_voltage": "0.00",
                    "rx_broadcast": 9975,
                    "rx_bytes": 347636709,
                    "rx_dropped": 8368,
                    "rx_errors": 0,
                    "rx_multicast": 11112,
                    "rx_packets": 2488745,
                    "satisfaction": 90,
                    "satisfaction_reason": 1,
                    "speed": 0,
                    "stp_pathcost": 0,
                    "stp_state": "disabled",
                    "tx_broadcast": 34134,
                    "tx_bytes": 3758924806,
                    "tx_dropped": 0,
                    "tx_errors": 0,
                    "tx_multicast": 333789,
                    "tx_packets": 3241268,
                    "up": false,
                    "tx_bytes-r": 0,
                    "rx_bytes-r": 0,
                    "bytes-r": 0,
                    "name": "2.3 Distribution Cabinet",
                    "port_security_mac_address": [],
                    "stp_port_mode": true,
                    "port_security_enabled": false,
                    "masked": false,
                    "aggregated_by": false
                },
                {
                    "port_idx": 12,
                    "media": "GE",
                    "port_poe": true,
                    "poe_caps": 7,
                    "speed_caps": 1048623,
                    "op_mode": "switch",
                    "portconf_id": "60717a89a61f7408a7706281",
                    "poe_mode": "off",
                    "anomalies": 0,
                    "autoneg": true,
                    "dot1x_mode": "unknown",
                    "dot1x_status": "disabled",
                    "enable": true,
                    "flowctrl_rx": false,
                    "flowctrl_tx": false,
                    "full_duplex": false,
                    "is_uplink": false,
                    "jumbo": false,
                    "mac_table": [],
                    "poe_class": "Unknown",
                    "poe_current": "0.00",
                    "poe_enable": false,
                    "poe_good": false,
                    "poe_power": "0.00",
                    "poe_voltage": "0.00",
                    "rx_broadcast": 0,
                    "rx_bytes": 0,
                    "rx_dropped": 0,
                    "rx_errors": 0,
                    "rx_multicast": 0,
                    "rx_packets": 0,
                    "satisfaction": 100,
                    "satisfaction_reason": 0,
                    "speed": 0,
                    "stp_pathcost": 0,
                    "stp_state": "disabled",
                    "tx_broadcast": 0,
                    "tx_bytes": 0,
                    "tx_dropped": 0,
                    "tx_errors": 0,
                    "tx_multicast": 0,
                    "tx_packets": 0,
                    "up": false,
                    "tx_bytes-r": 0,
                    "rx_bytes-r": 0,
                    "bytes-r": 0,
                    "name": "1.12 Children Room 1",
                    "port_security_mac_address": [],
                    "stp_port_mode": true,
                    "port_security_enabled": false,
                    "masked": false,
                    "aggregated_by": false
                },
                {
                    "port_idx": 13,
                    "media": "GE",
                    "port_poe": true,
                    "poe_caps": 7,
                    "speed_caps": 1048623,
                    "op_mode": "switch",
                    "portconf_id": "6070c964a61f7408a770605c",
                    "poe_mode": "off",
                    "anomalies": 0,
                    "autoneg": true,
                    "dot1x_mode": "unknown",
                    "dot1x_status": "disabled",
                    "enable": true,
                    "flowctrl_rx": false,
                    "flowctrl_tx": false,
                    "full_duplex": false,
                    "is_uplink": false,
                    "jumbo": false,
                    "mac_table": [],
                    "poe_class": "Unknown",
                    "poe_current": "0.00",
                    "poe_enable": false,
                    "poe_good": false,
                    "poe_power": "0.00",
                    "poe_voltage": "0.00",
                    "rx_broadcast": 0,
                    "rx_bytes": 0,
                    "rx_dropped": 0,
                    "rx_errors": 0,
                    "rx_multicast": 0,
                    "rx_packets": 0,
                    "satisfaction": 100,
                    "satisfaction_reason": 0,
                    "speed": 0,
                    "stp_pathcost": 0,
                    "stp_state": "disabled",
                    "tx_broadcast": 0,
                    "tx_bytes": 0,
                    "tx_dropped": 0,
                    "tx_errors": 0,
                    "tx_multicast": 0,
                    "tx_packets": 0,
                    "up": false,
                    "tx_bytes-r": 0,
                    "rx_bytes-r": 0,
                    "bytes-r": 0,
                    "stp_port_mode": true,
                    "port_security_mac_address": [],
                    "name": "1.13 Dining Room",
                    "masked": false,
                    "aggregated_by": false
                },
                {
                    "port_idx": 14,
                    "media": "GE",
                    "port_poe": true,
                    "poe_caps": 7,
                    "speed_caps": 1048623,
                    "op_mode": "switch",
                    "portconf_id": "6070c964a61f7408a770605c",
                    "poe_mode": "off",
                    "anomalies": 0,
                    "autoneg": true,
                    "dot1x_mode": "unknown",
                    "dot1x_status": "disabled",
                    "enable": true,
                    "flowctrl_rx": false,
                    "flowctrl_tx": false,
                    "full_duplex": false,
                    "is_uplink": false,
                    "jumbo": false,
                    "mac_table": [],
                    "poe_class": "Unknown",
                    "poe_current": "0.00",
                    "poe_enable": false,
                    "poe_good": false,
                    "poe_power": "0.00",
                    "poe_voltage": "0.00",
                    "rx_broadcast": 0,
                    "rx_bytes": 0,
                    "rx_dropped": 0,
                    "rx_errors": 0,
                    "rx_multicast": 0,
                    "rx_packets": 0,
                    "satisfaction": 100,
                    "satisfaction_reason": 0,
                    "speed": 0,
                    "stp_pathcost": 0,
                    "stp_state": "disabled",
                    "tx_broadcast": 0,
                    "tx_bytes": 0,
                    "tx_dropped": 0,
                    "tx_errors": 0,
                    "tx_multicast": 0,
                    "tx_packets": 0,
                    "up": false,
                    "tx_bytes-r": 0,
                    "rx_bytes-r": 0,
                    "bytes-r": 0,
                    "stp_port_mode": true,
                    "port_security_mac_address": [],
                    "name": "1.14 Bedroom",
                    "masked": false,
                    "aggregated_by": false
                },
                {
                    "port_idx": 15,
                    "media": "GE",
                    "port_poe": true,
                    "poe_caps": 7,
                    "speed_caps": 1048623,
                    "op_mode": "switch",
                    "portconf_id": "6070c964a61f7408a770605c",
                    "poe_mode": "off",
                    "anomalies": 0,
                    "autoneg": true,
                    "dot1x_mode": "unknown",
                    "dot1x_status": "disabled",
                    "enable": true,
                    "flowctrl_rx": false,
                    "flowctrl_tx": false,
                    "full_duplex": true,
                    "is_uplink": false,
                    "jumbo": false,
                    "mac_table": [
                        {
                            "age": 468,
                            "hostname": "Mac-mini",
                            "ip": "10.10.0.12",
                            "mac": "14:98:77:55:24:6e",
                            "static": false,
                            "uptime": 8844,
                            "vlan": 1,
                            "is_only_station_on_port": true
                        }
                    ],
                    "poe_class": "Unknown",
                    "poe_current": "0.00",
                    "poe_enable": false,
                    "poe_good": false,
                    "poe_power": "0.00",
                    "poe_voltage": "0.00",
                    "rx_broadcast": 4012,
                    "rx_bytes": 115309264975,
                    "rx_dropped": 64,
                    "rx_errors": 0,
                    "rx_multicast": 30627,
                    "rx_packets": 545127825,
                    "satisfaction": 90,
                    "satisfaction_reason": 1,
                    "speed": 1000,
                    "stp_pathcost": 20000,
                    "stp_state": "forwarding",
                    "tx_broadcast": 28795,
                    "tx_bytes": 740494374947,
                    "tx_dropped": 190,
                    "tx_errors": 0,
                    "tx_multicast": 348479,
                    "tx_packets": 530047446,
                    "up": true,
                    "tx_bytes-r": 2211759,
                    "rx_bytes-r": 44868,
                    "bytes-r": 2256628,
                    "name": "1.15 Workspace",
                    "stp_port_mode": true,
                    "port_security_mac_address": [],
                    "port_security_enabled": false,
                    "masked": false,
                    "aggregated_by": false
                },
                {
                    "port_idx": 16,
                    "media": "GE",
                    "port_poe": true,
                    "poe_caps": 7,
                    "speed_caps": 1048623,
                    "op_mode": "switch",
                    "portconf_id": "6070c964a61f7408a770605a",
                    "poe_mode": "off",
                    "anomalies": 0,
                    "autoneg": true,
                    "dot1x_mode": "unknown",
                    "dot1x_status": "disabled",
                    "enable": true,
                    "flowctrl_rx": false,
                    "flowctrl_tx": false,
                    "full_duplex": false,
                    "is_uplink": false,
                    "jumbo": false,
                    "mac_table": [],
                    "poe_class": "Unknown",
                    "poe_current": "0.00",
                    "poe_enable": false,
                    "poe_good": false,
                    "poe_power": "0.00",
                    "poe_voltage": "0.00",
                    "rx_broadcast": 2005,
                    "rx_bytes": 284470151,
                    "rx_dropped": 330,
                    "rx_errors": 2,
                    "rx_multicast": 3065,
                    "rx_packets": 401778,
                    "satisfaction": 75,
                    "satisfaction_reason": 3,
                    "speed": 0,
                    "stp_pathcost": 0,
                    "stp_state": "disabled",
                    "tx_broadcast": 13191,
                    "tx_bytes": 69248497,
                    "tx_dropped": 0,
                    "tx_errors": 0,
                    "tx_multicast": 47903,
                    "tx_packets": 441223,
                    "up": false,
                    "tx_bytes-r": 0,
                    "rx_bytes-r": 0,
                    "bytes-r": 0,
                    "name": "1.16 Workspace",
                    "port_security_mac_address": [],
                    "stp_port_mode": true,
                    "port_security_enabled": false,
                    "masked": false,
                    "aggregated_by": false
                },
                {
                    "port_idx": 17,
                    "media": "GE",
                    "port_poe": true,
                    "poe_caps": 7,
                    "speed_caps": 1048623,
                    "op_mode": "switch",
                    "portconf_id": "60c0bd9d0da23303beb7f793",
                    "poe_mode": "off",
                    "anomalies": 0,
                    "autoneg": true,
                    "dot1x_mode": "unknown",
                    "dot1x_status": "disabled",
                    "enable": true,
                    "flowctrl_rx": false,
                    "flowctrl_tx": false,
                    "full_duplex": true,
                    "is_uplink": false,
                    "jumbo": false,
                    "mac_table": [
                        {
                            "age": 4,
                            "hostname": "homeassistant",
                            "ip": "10.10.3.3",
                            "mac": "b8:27:eb:d5:5a:e4",
                            "static": false,
                            "uptime": 387403,
                            "vlan": 103,
                            "is_only_station_on_port": true
                        }
                    ],
                    "poe_class": "Unknown",
                    "poe_current": "0.00",
                    "poe_enable": false,
                    "poe_good": false,
                    "poe_power": "0.00",
                    "poe_voltage": "0.00",
                    "rx_broadcast": 302882,
                    "rx_bytes": 11857089872,
                    "rx_dropped": 48508,
                    "rx_errors": 0,
                    "rx_multicast": 76925,
                    "rx_packets": 17328254,
                    "satisfaction": 90,
                    "satisfaction_reason": 1,
                    "speed": 1000,
                    "stp_pathcost": 20000,
                    "stp_state": "forwarding",
                    "tx_broadcast": 52101,
                    "tx_bytes": 2494340831,
                    "tx_dropped": 0,
                    "tx_errors": 0,
                    "tx_multicast": 617119,
                    "tx_packets": 13465996,
                    "up": true,
                    "tx_bytes-r": 693,
                    "rx_bytes-r": 865,
                    "bytes-r": 1559,
                    "name": "Home Assistant",
                    "port_security_mac_address": [],
                    "stp_port_mode": true,
                    "port_security_enabled": false,
                    "masked": false,
                    "aggregated_by": false
                },
                {
                    "port_idx": 18,
                    "media": "GE",
                    "port_poe": true,
                    "poe_caps": 7,
                    "speed_caps": 1048623,
                    "op_mode": "switch",
                    "portconf_id": "6070c964a61f7408a770605c",
                    "poe_mode": "off",
                    "anomalies": 0,
                    "autoneg": true,
                    "dot1x_mode": "unknown",
                    "dot1x_status": "disabled",
                    "enable": true,
                    "flowctrl_rx": false,
                    "flowctrl_tx": false,
                    "full_duplex": true,
                    "is_uplink": false,
                    "jumbo": false,
                    "mac_table": [
                        {
                            "age": 24,
                            "hostname": "unifi",
                            "ip": "10.10.0.5",
                            "mac": "b8:27:eb:be:17:6b",
                            "static": false,
                            "uptime": 387403,
                            "vlan": 1,
                            "is_only_station_on_port": true
                        }
                    ],
                    "poe_class": "Unknown",
                    "poe_current": "0.00",
                    "poe_enable": false,
                    "poe_good": false,
                    "poe_power": "0.00",
                    "poe_voltage": "0.00",
                    "rx_broadcast": 636,
                    "rx_bytes": 37574491806,
                    "rx_dropped": 48809,
                    "rx_errors": 0,
                    "rx_multicast": 114317,
                    "rx_packets": 81916372,
                    "satisfaction": 90,
                    "satisfaction_reason": 1,
                    "speed": 100,
                    "stp_pathcost": 200000,
                    "stp_state": "forwarding",
                    "tx_broadcast": 58984,
                    "tx_bytes": 36666335437,
                    "tx_dropped": 7495,
                    "tx_errors": 0,
                    "tx_multicast": 646627,
                    "tx_packets": 83230891,
                    "up": true,
                    "tx_bytes-r": 114838,
                    "rx_bytes-r": 111614,
                    "bytes-r": 226453,
                    "name": "UniFi Controller",
                    "port_security_mac_address": [],
                    "stp_port_mode": true,
                    "port_security_enabled": false,
                    "masked": false,
                    "aggregated_by": false
                },
                {
                    "port_idx": 19,
                    "media": "GE",
                    "port_poe": true,
                    "poe_caps": 7,
                    "speed_caps": 1048623,
                    "op_mode": "switch",
                    "portconf_id": "60c0bd9d0da23303beb7f793",
                    "poe_mode": "off",
                    "anomalies": 0,
                    "autoneg": true,
                    "dot1x_mode": "unknown",
                    "dot1x_status": "disabled",
                    "enable": true,
                    "flowctrl_rx": false,
                    "flowctrl_tx": false,
                    "full_duplex": true,
                    "is_uplink": false,
                    "jumbo": false,
                    "mac_table": [
                        {
                            "age": 941,
                            "hostname": "ap440_0",
                            "ip": "10.10.3.2",
                            "mac": "00:60:b5:3f:53:b4",
                            "static": false,
                            "uptime": 993323,
                            "vlan": 103,
                            "is_only_station_on_port": true
                        }
                    ],
                    "poe_class": "Unknown",
                    "poe_current": "0.00",
                    "poe_enable": false,
                    "poe_good": false,
                    "poe_power": "0.00",
                    "poe_voltage": "0.00",
                    "rx_broadcast": 102,
                    "rx_bytes": 521225929,
                    "rx_dropped": 0,
                    "rx_errors": 0,
                    "rx_multicast": 356,
                    "rx_packets": 4605217,
                    "satisfaction": 100,
                    "satisfaction_reason": 0,
                    "speed": 100,
                    "stp_pathcost": 200000,
                    "stp_state": "forwarding",
                    "tx_broadcast": 355528,
                    "tx_bytes": 765467860,
                    "tx_dropped": 0,
                    "tx_errors": 0,
                    "tx_multicast": 645533,
                    "tx_packets": 6715683,
                    "up": true,
                    "tx_bytes-r": 753,
                    "rx_bytes-r": 521,
                    "bytes-r": 1275,
                    "name": "Heating Control",
                    "port_security_mac_address": [],
                    "stp_port_mode": true,
                    "port_security_enabled": false,
                    "masked": false,
                    "aggregated_by": false
                },
                {
                    "port_idx": 20,
                    "media": "GE",
                    "port_poe": true,
                    "poe_caps": 7,
                    "speed_caps": 1048623,
                    "op_mode": "switch",
                    "portconf_id": "6070c964a61f7408a770605c",
                    "poe_mode": "off",
                    "anomalies": 0,
                    "autoneg": true,
                    "dot1x_mode": "unknown",
                    "dot1x_status": "disabled",
                    "enable": true,
                    "flowctrl_rx": false,
                    "flowctrl_tx": false,
                    "full_duplex": false,
                    "is_uplink": false,
                    "jumbo": false,
                    "mac_table": [],
                    "poe_class": "Unknown",
                    "poe_current": "0.00",
                    "poe_enable": false,
                    "poe_good": false,
                    "poe_power": "0.00",
                    "poe_voltage": "0.00",
                    "rx_broadcast": 0,
                    "rx_bytes": 0,
                    "rx_dropped": 0,
                    "rx_errors": 0,
                    "rx_multicast": 0,
                    "rx_packets": 0,
                    "satisfaction": 100,
                    "satisfaction_reason": 0,
                    "speed": 0,
                    "stp_pathcost": 0,
                    "stp_state": "disabled",
                    "tx_broadcast": 0,
                    "tx_bytes": 0,
                    "tx_dropped": 0,
                    "tx_errors": 0,
                    "tx_multicast": 0,
                    "tx_packets": 0,
                    "up": false,
                    "tx_bytes-r": 0,
                    "rx_bytes-r": 0,
                    "bytes-r": 0,
                    "name": "2.20 Engineering Room",
                    "port_security_mac_address": [],
                    "stp_port_mode": true,
                    "port_security_enabled": false,
                    "masked": false,
                    "aggregated_by": false
                },
                {
                    "port_idx": 21,
                    "media": "GE",
                    "port_poe": true,
                    "poe_caps": 7,
                    "speed_caps": 1048623,
                    "op_mode": "switch",
                    "portconf_id": "60c0bd9d0da23303beb7f793",
                    "poe_mode": "off",
                    "anomalies": 0,
                    "autoneg": true,
                    "dot1x_mode": "unknown",
                    "dot1x_status": "disabled",
                    "enable": true,
                    "flowctrl_rx": false,
                    "flowctrl_tx": false,
                    "full_duplex": false,
                    "is_uplink": false,
                    "jumbo": false,
                    "mac_table": [],
                    "poe_class": "Unknown",
                    "poe_current": "0.00",
                    "poe_enable": false,
                    "poe_good": false,
                    "poe_power": "0.00",
                    "poe_voltage": "0.00",
                    "rx_broadcast": 1204,
                    "rx_bytes": 7844579,
                    "rx_dropped": 9413,
                    "rx_errors": 1,
                    "rx_multicast": 11198,
                    "rx_packets": 70539,
                    "satisfaction": 75,
                    "satisfaction_reason": 3,
                    "speed": 0,
                    "stp_pathcost": 0,
                    "stp_state": "disabled",
                    "tx_broadcast": 134179,
                    "tx_bytes": 138061924,
                    "tx_dropped": 0,
                    "tx_errors": 0,
                    "tx_multicast": 405496,
                    "tx_packets": 615648,
                    "up": false,
                    "tx_bytes-r": 0,
                    "rx_bytes-r": 0,
                    "bytes-r": 0,
                    "port_security_mac_address": [],
                    "name": "1.21 Kitchen",
                    "stp_port_mode": true,
                    "masked": false,
                    "aggregated_by": false
                },
                {
                    "port_idx": 22,
                    "media": "GE",
                    "port_poe": true,
                    "poe_caps": 7,
                    "speed_caps": 1048623,
                    "op_mode": "switch",
                    "portconf_id": "6070c964a61f7408a770605c",
                    "poe_mode": "off",
                    "anomalies": 0,
                    "autoneg": true,
                    "dot1x_mode": "unknown",
                    "dot1x_status": "disabled",
                    "enable": true,
                    "flowctrl_rx": false,
                    "flowctrl_tx": false,
                    "full_duplex": false,
                    "is_uplink": false,
                    "jumbo": false,
                    "mac_table": [],
                    "poe_class": "Unknown",
                    "poe_current": "0.00",
                    "poe_enable": false,
                    "poe_good": false,
                    "poe_power": "0.00",
                    "poe_voltage": "0.00",
                    "rx_broadcast": 0,
                    "rx_bytes": 0,
                    "rx_dropped": 0,
                    "rx_errors": 0,
                    "rx_multicast": 0,
                    "rx_packets": 0,
                    "satisfaction": 100,
                    "satisfaction_reason": 0,
                    "speed": 0,
                    "stp_pathcost": 0,
                    "stp_state": "disabled",
                    "tx_broadcast": 0,
                    "tx_bytes": 0,
                    "tx_dropped": 0,
                    "tx_errors": 0,
                    "tx_multicast": 0,
                    "tx_packets": 0,
                    "up": false,
                    "tx_bytes-r": 0,
                    "rx_bytes-r": 0,
                    "bytes-r": 0,
                    "port_security_mac_address": [],
                    "name": "N/A",
                    "stp_port_mode": true,
                    "masked": false,
                    "aggregated_by": false
                },
                {
                    "port_idx": 23,
                    "media": "GE",
                    "port_poe": true,
                    "poe_caps": 7,
                    "speed_caps": 1048623,
                    "op_mode": "switch",
                    "portconf_id": "6070c964a61f7408a770605a",
                    "poe_mode": "off",
                    "anomalies": 0,
                    "autoneg": true,
                    "dot1x_mode": "unknown",
                    "dot1x_status": "disabled",
                    "enable": true,
                    "flowctrl_rx": false,
                    "flowctrl_tx": false,
                    "full_duplex": true,
                    "is_uplink": true,
                    "jumbo": false,
                    "mac_table": [
                        {
                            "age": 100086,
                            "ip": "10.10.4.1",
                            "mac": "00:0d:b9:52:45:50",
                            "static": false,
                            "uptime": 464796,
                            "vlan": 104,
                            "port_delta": {
                                "time_delta": 30,
                                "time_delta_activity": 30,
                                "tx_bytes": 3265654,
                                "rx_bytes": 3338683,
                                "tx_packets": 7052,
                                "rx_packets": 6791
                            },
                            "is_only_station_on_port": true
                        },
                        {
                            "age": 1892,
                            "ip": "10.10.3.1",
                            "mac": "00:0d:b9:52:45:50",
                            "static": false,
                            "uptime": 464809,
                            "vlan": 103
                        },
                        {
                            "age": 258739,
                            "ip": "10.10.2.1",
                            "mac": "00:0d:b9:52:45:50",
                            "static": false,
                            "uptime": 315660,
                            "vlan": 102
                        },
                        {
                            "age": 55901,
                            "mac": "00:0d:b9:52:45:50",
                            "static": false,
                            "uptime": 55901,
                            "vlan": 101
                        },
                        {
                            "age": 24,
                            "ip": "10.10.0.1",
                            "mac": "00:0d:b9:52:45:50",
                            "static": false,
                            "uptime": 464807,
                            "vlan": 1
                        }
                    ],
                    "poe_class": "Unknown",
                    "poe_current": "0.00",
                    "poe_enable": false,
                    "poe_good": false,
                    "poe_power": "0.00",
                    "poe_voltage": "0.00",
                    "rx_broadcast": 61931,
                    "rx_bytes": 197836717150,
                    "rx_dropped": 32672,
                    "rx_errors": 0,
                    "rx_multicast": 251393,
                    "rx_packets": 191976683,
                    "satisfaction": 90,
                    "satisfaction_reason": 1,
                    "speed": 1000,
                    "stp_pathcost": 20000,
                    "stp_state": "forwarding",
                    "tx_broadcast": 401569,
                    "tx_bytes": 44168593129,
                    "tx_dropped": 0,
                    "tx_errors": 0,
                    "tx_multicast": 810685,
                    "tx_packets": 152092398,
                    "up": true,
                    "tx_bytes-r": 108855,
                    "rx_bytes-r": 111289,
                    "bytes-r": 220144,
                    "stp_port_mode": true,
                    "name": "Uplink",
                    "port_security_mac_address": [],
                    "masked": false,
                    "aggregated_by": false
                },
                {
                    "port_idx": 24,
                    "media": "GE",
                    "port_poe": true,
                    "poe_caps": 7,
                    "speed_caps": 1048623,
                    "op_mode": "switch",
                    "portconf_id": "622204f0cbfa12042d704038",
                    "poe_mode": "off",
                    "anomalies": 0,
                    "autoneg": true,
                    "dot1x_mode": "unknown",
                    "dot1x_status": "disabled",
                    "enable": true,
                    "flowctrl_rx": false,
                    "flowctrl_tx": false,
                    "full_duplex": true,
                    "is_uplink": false,
                    "jumbo": false,
                    "mac_table": [
                        {
                            "age": 3329,
                            "hostname": "mediabox-103",
                            "ip": "10.10.3.16",
                            "mac": "de:c3:da:5f:14:0c",
                            "static": false,
                            "uptime": 993328,
                            "vlan": 103,
                            "port_delta": {
                                "time_delta": 30,
                                "time_delta_activity": 30,
                                "tx_bytes": 1243235,
                                "rx_bytes": 66260038,
                                "tx_packets": 11287,
                                "rx_packets": 45452
                            },
                            "is_only_station_on_port": true
                        },
                        {
                            "age": 3336,
                            "hostname": "mediabox",
                            "ip": "10.10.0.3",
                            "mac": "de:c3:da:5f:14:0c",
                            "static": false,
                            "uptime": 993331,
                            "vlan": 1
                        }
                    ],
                    "poe_class": "Unknown",
                    "poe_current": "0.00",
                    "poe_enable": false,
                    "poe_good": false,
                    "poe_power": "0.00",
                    "poe_voltage": "0.00",
                    "rx_broadcast": 35932,
                    "rx_bytes": 693908404694,
                    "rx_dropped": 65349,
                    "rx_errors": 0,
                    "rx_multicast": 105996,
                    "rx_packets": 493124321,
                    "satisfaction": 90,
                    "satisfaction_reason": 1,
                    "speed": 1000,
                    "stp_pathcost": 20000,
                    "stp_state": "forwarding",
                    "tx_broadcast": 380872,
                    "tx_bytes": 124502162580,
                    "tx_dropped": 345,
                    "tx_errors": 0,
                    "tx_multicast": 793134,
                    "tx_packets": 513850864,
                    "up": true,
                    "tx_bytes-r": 41441,
                    "rx_bytes-r": 2208667,
                    "bytes-r": 2250109,
                    "name": "NAS",
                    "port_security_mac_address": [],
                    "stp_port_mode": true,
                    "port_security_enabled": false,
                    "masked": false,
                    "aggregated_by": false
                },
                {
                    "port_idx": 25,
                    "media": "SFP",
                    "port_poe": false,
                    "poe_caps": 0,
                    "speed_caps": 1048608,
                    "op_mode": "switch",
                    "portconf_id": "6070c964a61f7408a770605b",
                    "anomalies": 0,
                    "autoneg": true,
                    "dot1x_mode": "unknown",
                    "dot1x_status": "disabled",
                    "enable": false,
                    "flowctrl_rx": false,
                    "flowctrl_tx": false,
                    "full_duplex": false,
                    "is_uplink": false,
                    "jumbo": false,
                    "mac_table": [],
                    "rx_broadcast": 0,
                    "rx_bytes": 0,
                    "rx_dropped": 0,
                    "rx_errors": 0,
                    "rx_multicast": 0,
                    "rx_packets": 0,
                    "satisfaction": 100,
                    "satisfaction_reason": 0,
                    "sfp_found": false,
                    "speed": 0,
                    "stp_pathcost": 0,
                    "stp_state": "disabled",
                    "tx_broadcast": 0,
                    "tx_bytes": 0,
                    "tx_dropped": 0,
                    "tx_errors": 0,
                    "tx_multicast": 0,
                    "tx_packets": 0,
                    "up": false,
                    "tx_bytes-r": 0,
                    "rx_bytes-r": 0,
                    "bytes-r": 0,
                    "stp_port_mode": true,
                    "port_security_mac_address": [],
                    "name": "SFP 1",
                    "masked": false,
                    "aggregated_by": false
                },
                {
                    "port_idx": 26,
                    "media": "SFP",
                    "port_poe": false,
                    "poe_caps": 0,
                    "speed_caps": 1048608,
                    "op_mode": "switch",
                    "portconf_id": "6070c964a61f7408a770605b",
                    "anomalies": 0,
                    "autoneg": true,
                    "dot1x_mode": "unknown",
                    "dot1x_status": "disabled",
                    "enable": false,
                    "flowctrl_rx": false,
                    "flowctrl_tx": false,
                    "full_duplex": false,
                    "is_uplink": false,
                    "jumbo": false,
                    "mac_table": [],
                    "rx_broadcast": 0,
                    "rx_bytes": 0,
                    "rx_dropped": 0,
                    "rx_errors": 0,
                    "rx_multicast": 0,
                    "rx_packets": 0,
                    "satisfaction": 100,
                    "satisfaction_reason": 0,
                    "sfp_found": false,
                    "speed": 0,
                    "stp_pathcost": 0,
                    "stp_state": "disabled",
                    "tx_broadcast": 0,
                    "tx_bytes": 0,
                    "tx_dropped": 0,
                    "tx_errors": 0,
                    "tx_multicast": 0,
                    "tx_packets": 0,
                    "up": false,
                    "tx_bytes-r": 0,
                    "rx_bytes-r": 0,
                    "bytes-r": 0,
                    "port_security_mac_address": [],
                    "stp_port_mode": true,
                    "name": "SFP 2",
                    "masked": false,
                    "aggregated_by": false
                }
            ],
            "power_source_ctrl_enabled": false,
            "provisioned_at": 1660056204,
            "required_version": "4.0.72",
            "satisfaction": 93,
            "serial": "MOCKED SN",
            "setup_id": "db2faf9c-bfc9-4a4d-94c7-42b1c7c8807a",
            "site_id": "MOCKED_SITE_ID",
            "snmp_contact": "",
            "snmp_location": "",
            "stp_priority": "32768",
            "stp_version": "rstp",
            "switch_caps": {
                "feature_caps": 33790,
                "max_mirror_sessions": 1,
                "max_aggregate_sessions": 13,
                "max_l3_intf": 0,
                "max_reserved_routes": 0,
                "max_static_routes": 0
            },
            "sys_error_caps": 0,
            "syslog_key": "b99aa2e7fc09fa7e4579fc4f188d343d44d2016feb8da5fab93ff0137c44ffbe",
            "two_phase_adopt": false,
            "type": "usw",
            "unsupported": false,
            "unsupported_reason": 0,
            "version": "6.2.14.13855",
            "x_aes_gcm": true,
            "x_authkey": "fa2cac41b3392b94ead02f7b19b7dd3c",
            "x_fingerprint": "36:ee:f1:e7:8a:35:74:57:62:20:38:6e:88:a9:ba:49:f7:49:6c:87",
            "x_ssh_hostkey_fingerprint": "ac:18:57:5a:c7:df:b3:91:32:62:65:b0:b5:0e:cf:dd",
            "device_id": "MOCKED_DEVICE_ID",
            "state": 1,
            "start_disconnected_millis": 1659811081133,
            "default": false,
            "discovered_via": "l2",
            "adopt_ip": "10.10.0.2",
            "adopt_url": "http://10.10.0.5:8080/inform",
            "last_seen": 1660156344,
            "min_inform_interval_seconds": 30,
            "upgradable": false,
            "adoptable_when_upgraded": false,
            "rollupgrade": false,
            "known_cfgversion": "9b584e5b55742366",
            "uptime": 9221294,
            "_uptime": 9221294,
            "locating": false,
            "start_connected_millis": 1659811098608,
            "prev_non_busy_state": 5,
            "next_interval": 30,
            "connect_request_ip": "10.10.0.2",
            "connect_request_port": "43193",
            "sys_stats": {
                "loadavg_1": "1.92",
                "loadavg_15": "1.90",
                "loadavg_5": "1.97",
                "mem_buffer": 0,
                "mem_total": 262381568,
                "mem_used": 101146624
            },
            "system-stats": {
                "cpu": "58.6",
                "mem": "38.5",
                "uptime": "9221292"
            },
            "ssh_session_table": [],
            "lldp_table": [],
            "displayable_version": "6.2.14",
            "connection_network_name": "100 Wired",
            "startup_timestamp": 1650935051,
            "is_access_point": false,
            "fan_level": 50,
            "general_temperature": 44,
            "overheating": false,
            "total_max_power": 222,
            "downlink_table": [],
            "uplink": {
                "full_duplex": true,
                "ip": "10.10.0.2",
                "mac": "b4:fb:e4:b6:6f:12",
                "name": "eth0",
                "netmask": "255.255.255.0",
                "num_port": 26,
                "rx_bytes": 197836717150,
                "rx_dropped": 32672,
                "rx_errors": 0,
                "rx_multicast": 0,
                "rx_packets": 191976683,
                "speed": 1000,
                "tx_bytes": 44168593129,
                "tx_dropped": 0,
                "tx_errors": 0,
                "tx_packets": 152092398,
                "up": true,
                "port_idx": 23,
                "media": "GE",
                "max_speed": 1000,
                "type": "wire",
                "tx_bytes-r": 108855,
                "rx_bytes-r": 111289,
                "uplink_source": "legacy"
            },
            "uplink_depth": 1,
            "dhcp_server_table": [],
            "stat": {
                "sw": {
                    "site_id": "6070c958a61f7408a7706045",
                    "o": "sw",
                    "oid": "b4:fb:e4:b6:6f:12",
                    "sw": "b4:fb:e4:b6:6f:12",
                    "time": 1659810900000,
                    "datetime": "2022-08-06T18:35:00Z",
                    "rx_packets": 5.32184491E8,
                    "rx_bytes": 3.65520364634E11,
                    "rx_errors": 2.0,
                    "rx_dropped": 90251.0,
                    "rx_crypts": 0.0,
                    "rx_frags": 0.0,
                    "tx_packets": 5.34546812E8,
                    "tx_bytes": 3.65787119179E11,
                    "tx_errors": 0.0,
                    "tx_dropped": 7986.0,
                    "tx_retries": 0.0,
                    "rx_multicast": 243312.0,
                    "rx_broadcast": 167629.0,
                    "tx_multicast": 2109596.0,
                    "tx_broadcast": 649372.0,
                    "bytes": 7.31307483813E11,
                    "duration": 3.4521E8,
                    "port_1-tx_packets": 252643.0,
                    "port_1-tx_bytes": 2.8950692E7,
                    "port_1-tx_multicast": 162609.0,
                    "port_2-rx_packets": 1091061.0,
                    "port_2-rx_bytes": 3.45292656E8,
                    "port_2-rx_dropped": 11380.0,
                    "port_2-tx_packets": 1712177.0,
                    "port_2-tx_bytes": 1.80328541E8,
                    "port_2-rx_multicast": 14208.0,
                    "port_2-tx_multicast": 248062.0,
                    "port_2-tx_broadcast": 20618.0,
                    "port_15-rx_packets": 1.8298847E8,
                    "port_15-rx_bytes": 3.1716781209E10,
                    "port_15-tx_packets": 1.71216353E8,
                    "port_15-tx_bytes": 2.37528449442E11,
                    "port_15-rx_multicast": 11952.0,
                    "port_15-tx_multicast": 116298.0,
                    "port_15-tx_broadcast": 9505.0,
                    "port_17-rx_packets": 5562600.0,
                    "port_17-rx_bytes": 3.922492626E9,
                    "port_17-rx_dropped": 17072.0,
                    "port_17-tx_packets": 3861188.0,
                    "port_17-tx_bytes": 5.81183863E8,
                    "port_17-rx_multicast": 25574.0,
                    "port_17-rx_broadcast": 97894.0,
                    "port_17-tx_multicast": 216275.0,
                    "port_18-rx_packets": 7.8471511E7,
                    "port_18-rx_bytes": 3.5752637412E10,
                    "port_18-rx_dropped": 17070.0,
                    "port_18-tx_packets": 7.9941617E7,
                    "port_18-tx_bytes": 3.6065099519E10,
                    "port_18-rx_multicast": 38475.0,
                    "port_18-tx_multicast": 229484.0,
                    "port_18-tx_broadcast": 20428.0,
                    "port_19-rx_packets": 1603528.0,
                    "port_19-rx_bytes": 1.83256589E8,
                    "port_19-tx_packets": 2344967.0,
                    "port_19-tx_bytes": 2.67304486E8,
                    "port_19-tx_multicast": 224649.0,
                    "port_19-tx_broadcast": 129688.0,
                    "port_21-rx_packets": 25332.0,
                    "port_21-rx_bytes": 2761733.0,
                    "port_21-tx_packets": 212727.0,
                    "port_21-tx_bytes": 4.7317433E7,
                    "port_21-rx_multicast": 4175.0,
                    "port_21-tx_multicast": 139580.0,
                    "port_21-tx_broadcast": 47413.0,
                    "port_23-rx_packets": 1.19441433E8,
                    "port_23-rx_bytes": 1.03013291414E11,
                    "port_23-rx_dropped": 11380.0,
                    "port_23-tx_packets": 1.08950803E8,
                    "port_23-tx_bytes": 3.7588998761E10,
                    "port_23-rx_multicast": 92316.0,
                    "port_23-tx_multicast": 282028.0,
                    "port_23-tx_broadcast": 131187.0,
                    "port_24-rx_packets": 1.35340937E8,
                    "port_24-rx_bytes": 1.89876174838E11,
                    "port_24-rx_dropped": 22760.0,
                    "port_24-tx_packets": 1.51593354E8,
                    "port_24-tx_bytes": 3.2680110024E10,
                    "port_24-rx_multicast": 37290.0,
                    "port_24-tx_multicast": 277156.0,
                    "port_24-tx_broadcast": 137882.0,
                    "port_1-rx_packets": 49345.0,
                    "port_1-rx_bytes": 7050393.0,
                    "port_1-rx_multicast": 573.0,
                    "port_17-tx_broadcast": 31794.0,
                    "port_24-rx_broadcast": 12451.0,
                    "port_15-rx_broadcast": 1300.0,
                    "port_21-rx_broadcast": 465.0,
                    "port_21-rx_dropped": 3537.0,
                    "port_18-rx_broadcast": 217.0,
                    "port_19-rx_multicast": 127.0,
                    "port_18-tx_dropped": 7495.0,
                    "port_3-tx_packets": 964.0,
                    "port_3-tx_bytes": 206966.0,
                    "port_3-tx_multicast": 572.0,
                    "port_3-tx_broadcast": 44.0,
                    "port_3-rx_packets": 532.0,
                    "port_3-rx_bytes": 139572.0,
                    "port_3-rx_multicast": 97.0,
                    "port_3-rx_broadcast": 46.0,
                    "port_1-tx_broadcast": 46383.0,
                    "port_23-rx_broadcast": 45691.0,
                    "port_3-rx_dropped": 4.0,
                    "port_11-tx_packets": 1504042.0,
                    "port_11-tx_bytes": 1.829192668E9,
                    "port_11-tx_multicast": 123309.0,
                    "port_11-tx_broadcast": 23144.0,
                    "port_11-rx_packets": 1391483.0,
                    "port_11-rx_bytes": 1.61083574E8,
                    "port_11-rx_broadcast": 3700.0,
                    "port_11-rx_dropped": 3153.0,
                    "port_11-rx_multicast": 4125.0,
                    "port_15-rx_dropped": 26.0,
                    "port_1-rx_broadcast": 3055.0,
                    "port_1-rx_dropped": 12.0,
                    "port_16-tx_packets": 203280.0,
                    "port_16-tx_bytes": 2.9818516E7,
                    "port_16-tx_multicast": 37192.0,
                    "port_16-rx_packets": 158210.0,
                    "port_16-rx_bytes": 8.8962569E7,
                    "port_16-rx_multicast": 1567.0,
                    "port_16-rx_broadcast": 1689.0,
                    "port_16-tx_broadcast": 11702.0,
                    "port_2-rx_broadcast": 27.0,
                    "port_4-tx_packets": 1.266206E7,
                    "port_4-tx_bytes": 1.8949027308E10,
                    "port_4-tx_multicast": 26566.0,
                    "port_6-tx_packets": 90637.0,
                    "port_6-tx_bytes": 1.113096E7,
                    "port_6-tx_multicast": 25816.0,
                    "port_4-rx_packets": 5976115.0,
                    "port_4-rx_bytes": 4.40571279E8,
                    "port_4-rx_multicast": 5522.0,
                    "port_4-rx_broadcast": 1044.0,
                    "port_4-rx_dropped": 903.0,
                    "port_6-rx_packets": 83934.0,
                    "port_6-rx_bytes": 9868770.0,
                    "port_6-rx_multicast": 7311.0,
                    "port_4-tx_broadcast": 18979.0,
                    "port_6-rx_broadcast": 50.0,
                    "port_6-tx_broadcast": 20605.0,
                    "port_6-rx_dropped": 2930.0,
                    "port_16-rx_dropped": 24.0,
                    "port_4-rx_errors": 1.0,
                    "port_15-tx_dropped": 190.0,
                    "port_24-tx_dropped": 301.0,
                    "port_21-rx_errors": 1.0
                }
            },
            "tx_bytes": 197836717150,
            "rx_bytes": 44168593129,
            "bytes": 242005310279,
            "num_sta": 9,
            "user-num_sta": 9,
            "guest-num_sta": 0,
            "x_has_ssh_hostkey": true
        }
    ]
}"""

happy_path_port_overrides_payload: str = """{
    "port_overrides": [
        {
            "name": "MOCKED Port 1",
            "port_idx": 1,
            "poe_mode": "pasv24",
            "portconf_id": "60c0bdca0da23303beb7f799",
            "port_security_mac_address": [],
            "stp_port_mode": true,
            "autoneg": true,
            "port_security_enabled": false
        },
        {
            "name": "MOCKED Port 2",
            "port_idx": 2,
            "poe_mode": "off",
            "portconf_id": "6070c964a61f7408a770605c",
            "port_security_mac_address": [],
            "stp_port_mode": true,
            "autoneg": true,
            "port_security_enabled": false
        },
        {
            "name": "MOCKED Port 3",
            "port_idx": 3,
            "poe_mode": "auto",
            "portconf_id": "6070c964a61f7408a770605a",
            "port_security_mac_address": [],
            "stp_port_mode": true,
            "autoneg": true,
            "port_security_enabled": false
        },
        {
            "name": "MOCKED Port 4",
            "port_idx": 4,
            "poe_mode": "off",
            "portconf_id": "60c0bd9d0da23303beb7f793",
            "port_security_mac_address": [],
            "stp_port_mode": true,
            "autoneg": true
        },
        {
            "stp_port_mode": true,
            "autoneg": true,
            "port_idx": 5,
            "name": "MOCKED Port 5",
            "poe_mode": "off",
            "portconf_id": "6070c964a61f7408a770605c",
            "port_security_mac_address": []
        },
        {
            "name": "MOCKED Port 6",
            "port_security_mac_address": [],
            "stp_port_mode": true,
            "portconf_id": "60c0bd9d0da23303beb7f793",
            "autoneg": true,
            "port_idx": 6,
            "poe_mode": "off"
        },
        {
            "poe_mode": "off",
            "stp_port_mode": true,
            "port_security_mac_address": [],
            "port_idx": 7,
            "portconf_id": "6070c964a61f7408a770605c",
            "name": "MOCKED Port 7",
            "autoneg": true
        },
        {
            "name": "MOCKED Port 8",
            "port_idx": 8,
            "poe_mode": "auto",
            "portconf_id": "6070c964a61f7408a770605c"
        },
        {
            "port_security_enabled": false,
            "autoneg": true,
            "portconf_id": "60717a89a61f7408a7706281",
            "stp_port_mode": true,
            "port_idx": 9,
            "poe_mode": "off",
            "name": "MOCKED Port 9",
            "port_security_mac_address": []
        },
        {
            "name": "MOCKED Port 10",
            "autoneg": true,
            "portconf_id": "60717a89a61f7408a7706281",
            "poe_mode": "off",
            "port_idx": 10,
            "stp_port_mode": true,
            "port_security_mac_address": [],
            "port_security_enabled": false
        },
        {
            "name": "MOCKED Port 11",
            "port_idx": 11,
            "poe_mode": "off",
            "portconf_id": "60c0bd9d0da23303beb7f793",
            "port_security_mac_address": [],
            "stp_port_mode": true,
            "autoneg": true,
            "port_security_enabled": false
        },
        {
            "name": "MOCKED Port 12",
            "port_idx": 12,
            "poe_mode": "off",
            "portconf_id": "60717a89a61f7408a7706281",
            "port_security_mac_address": [],
            "stp_port_mode": true,
            "autoneg": true,
            "port_security_enabled": false
        },
        {
            "autoneg": true,
            "stp_port_mode": true,
            "portconf_id": "6070c964a61f7408a770605c",
            "poe_mode": "off",
            "port_idx": 13,
            "port_security_mac_address": [],
            "name": "MOCKED Port 13"
        },
        {
            "portconf_id": "6070c964a61f7408a770605c",
            "autoneg": true,
            "stp_port_mode": true,
            "port_security_mac_address": [],
            "name": "MOCKED Port 14",
            "port_idx": 14,
            "poe_mode": "off"
        },
        {
            "port_idx": 15,
            "name": "MOCKED Port 15",
            "autoneg": true,
            "poe_mode": "off",
            "stp_port_mode": true,
            "port_security_mac_address": [],
            "portconf_id": "6070c964a61f7408a770605c",
            "port_security_enabled": false
        },
        {
            "name": "MOCKED Port 16",
            "port_idx": 16,
            "poe_mode": "off",
            "portconf_id": "60c0bdca0da23303beb7f799",
            "port_security_mac_address": [],
            "stp_port_mode": true,
            "autoneg": true,
            "port_security_enabled": false
        },
        {
            "name": "MOCKED Port 17",
            "port_idx": 17,
            "poe_mode": "auto",
            "portconf_id": "60c0bd9d0da23303beb7f793",
            "port_security_mac_address": [],
            "stp_port_mode": true,
            "autoneg": true,
            "port_security_enabled": false
        },
        {
            "name": "MOCKED Port 18",
            "port_idx": 18,
            "poe_mode": "off",
            "portconf_id": "6070c964a61f7408a770605c",
            "port_security_mac_address": [],
            "stp_port_mode": true,
            "autoneg": true,
            "port_security_enabled": false
        },
        {
            "autoneg": true,
            "port_security_mac_address": [],
            "stp_port_mode": true,
            "poe_mode": "off",
            "name": "Port 19",
            "portconf_id": "60c0bd9d0da23303beb7f793",
            "port_idx": 19
        },
        {
            "name": "MOCKED Port 20",
            "port_idx": 20,
            "poe_mode": "off",
            "portconf_id": "6070c964a61f7408a770605c",
            "port_security_mac_address": [],
            "stp_port_mode": true,
            "autoneg": true,
            "port_security_enabled": false
        },
        {
            "autoneg": true,
            "port_idx": 21,
            "port_security_mac_address": [],
            "portconf_id": "60c0bd9d0da23303beb7f793",
            "name": "MOCKED Port 21",
            "poe_mode": "off",
            "stp_port_mode": true
        },
        {
            "port_idx": 22,
            "poe_mode": "off",
            "port_security_mac_address": [],
            "autoneg": true,
            "name": "MOCKED Port 22",
            "portconf_id": "6070c964a61f7408a770605c",
            "stp_port_mode": true
        },
        {
            "portconf_id": "6070c964a61f7408a770605a",
            "autoneg": true,
            "poe_mode": "off",
            "port_idx": 23,
            "stp_port_mode": true,
            "name": "MOCKED Port 23",
            "port_security_mac_address": []
        },
        {
            "name": "MOCKED Port 24",
            "port_idx": 24,
            "poe_mode": "off",
            "portconf_id": "622204f0cbfa12042d704038",
            "port_security_mac_address": [],
            "stp_port_mode": true,
            "autoneg": true,
            "port_security_enabled": false
        },
        {
            "stp_port_mode": true,
            "autoneg": true,
            "port_idx": 25,
            "port_security_mac_address": [],
            "portconf_id": "6070c964a61f7408a770605b"
        },
        {
            "port_security_mac_address": [],
            "autoneg": true,
            "portconf_id": "6070c964a61f7408a770605b",
            "stp_port_mode": true,
            "port_idx": 26
        }
    ]
}"""

response_header: dict = {
    "Accept": "application/json",
    "Content-Type": "application/json; charset=utf-8",
}
