name: Upload Python Package

on:
  push:
    tags:
      - '*'

jobs:
  check-tag:
    runs-on: ubuntu-latest
    outputs:
      release-type: ${{ steps.check-tag.outputs.run_jobs }}
    steps:
      - name: check tag ${{ github.ref }}
        id: check-tag
        run: |
          if [[ ${{ github.event.ref }} =~ ^refs\/tags\/[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo ::set-output name=run_jobs::release
          elif [[ ${{ github.event.ref }} =~ ^refs\/tags\/[0-9]+\.[0-9]+\.[0-9]+-beta[0-9]+$ ]]; then
            echo ::set-output name=run_jobs::prerelease
          fi

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade pipenv
        pip install build
        pipenv install --deploy --dev
    - name: Check code format with black
      run: pipenv run black --diff --check $(git ls-files '*.py')
#    - name: Lint with flake8
#      run: pipenv run flake8 $(git ls-files '*.py') --show-source --statistics
    - name: Lint with mypy
      run: pipenv run mypy $(git ls-files '*.py')
    - name: Run tests
      run: pipenv run pytest

  deploy:
    needs: [check-tag]
    if: needs.check-tag.outputs.release-type == 'release' || needs.check-tag.outputs.release-type == 'prerelease'
    runs-on: ubuntu-latest
    steps:
    - name: Build package
      run: python -m build
    - name: Publish test package
      if: needs.check-tag.outputs.release-type == 'prerelease'
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        user: __token__
        password: ${{ secrets.PYPI_TEST_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/
        verbose: true
    - name: Publish package
      if: needs.check-tag.outputs.release-type == 'release'
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
